version: "3.4"
services:
  client:
    image: sherlockucf.azurecr.io/client:prod
    container_name: client
    build:
      context: client
      target: client-prod
    environment:
      PORT: "80"
      TWINE_PORT: "80"
      REACT_APP_PROTOCOL: "http"
      REACT_APP_DOMAIN: "localhost"
      MONGO_DOMAIN: "mongo"
      # CHOKIDAR_USEPOLLING: "true"
    ports:
      - 127.0.0.1:80:80
    depends_on: 
      - twine 
      - api
    
      
  twine:
    image: sherlockucf.azurecr.io/twine:prod
    container_name: twine
    build:
      context: client/modules/twine
      dockerfile: Dockerfile
      target: twine-prod

  api:
    image: api:prod
    build:
      context: server
      target: api-prod
    container_name: api
    environment:
      NODE_APACHE_PASSWORD: "Basic "
      PROTOCOL: "https"
      MONGO_HOST: "mongo"
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      # NODE_ENV: production
    volumes:
      - /usr/node_modules
    command: ["node", "dist/server.js"]
    depends_on: 
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - dbdata:/data/db
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: drowssap
      MONGO_INITDB_DATABASE: sherlock_dev

volumes:
  dbdata:
