export default {
  seconds: 10,
  frame: 0.0333,
  playOrPause: " ",
  forward_x_seconds: "f",
  rewind_x_seconds: "r",
  nextFrame: "ArrowRight",
  prevFrame: "ArrowLeft",
  toggleSingleVideoMode: "s",
  nextVideo: "n",
  prevVideo: "p",
  toggleSubject1: "1",
  toggleSubject2: "2",
  toggleSubject3: "3",
  toggleSubject4: "4",
  toggleSubject5: "5",
  restart: "0",
  escape: "Escape",
};
